<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>14</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Ryze.Domain\Ryze.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="FluentValidation" Version="12.1.1" />
      <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
      <PackageReference Include="Mapster" Version="10.0.0-pre01" />
      <PackageReference Include="ModularityKit.Context" Version="1.0.0-preview.1" />
      <PackageReference Include="ModularityKit.Context.AspNet" Version="1.0.0-preview.1" />
      <PackageReference Include="ModularityKit.Mutator" Version="1.9.0" />
      <PackageReference Include="OpenTelemetry" Version="1.14.0" />
      <PackageReference Include="Polly" Version="8.7.0" />
      <PackageReference Include="Ryzespace.Contracts.Shared" Version="1.0.1" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Features\Requests\Services\" />
      <Folder Include="Features\Transfer\UseCase\Commands\Validations\" />
    </ItemGroup>
</Project>
