using Ryze.Domain.Features.Ledger.Enum;

namespace Ryze.Domain.Features.Ledger.Entity.ChartsAccounts;

public static partial class ChartOfAccounts
{
    /// <summary>
    /// Expense account used to track operational costs related to banking,
    /// payment processors, and external gateway services.
    /// </summary>
    /// <remarks>
    /// Represents platform expenses generated by financial infrastructure,
    /// including transaction processing fees, bank charges, and gateway costs.
    /// These expenses reduce platform profitability and are recorded as debit normal accounts.
    /// </remarks>
    public static readonly LedgerAccount ExpenseBankingFees = new()
    {
        Id = "expense:platform:banking",
        Name = "Expense - Banking & Gateway Fees",
        AccountType = "platform_expense",
        Category = AccountCategory.Expense
    };

    /// <summary>
    /// Expense account used to record losses caused by fraud events,
    /// chargebacks, and manually approved write-offs.
    /// </summary>
    /// <remarks>
    /// Tracks financial impact from unrecoverable balances,
    /// fraudulent activity, and exceptional account adjustments.
    /// Entries posted here represent operational losses recognized
    /// </remarks>
    public static readonly LedgerAccount ExpenseFraudLosses = new()
    {
        Id = "expense:platform:fraud",
        Name = "Expense - Fraud & Manual Write-offs",
        AccountType = "platform_expense",
        Category = AccountCategory.Expense
    };
}