using Ryze.Domain.Features.Ledger.Enum;

namespace Ryze.Domain.Features.Ledger.Entity.ChartsAccounts;

public static partial class ChartOfAccounts
{
    /// <summary>
    /// Transit asset account used for funds received through external payment
    /// gateways before final settlement.
    /// </summary>
    /// <remarks>
    /// Represents temporary custody of incoming funds that have been confirmed
    /// by a payment provider but have not yet been transferred to the platform
    /// treasury account.
    ///
    /// Commonly used during asynchronous settlement flows where payment capture
    /// and bank settlement occur at different times.
    /// </remarks>
    public static readonly LedgerAccount PaymentGatewayTransit = new()
    {
        Id = "asset:transit:gateway",
        Name = "Payment Gateway Transit (Unsettled Inbound)",
        AccountType = "transit_asset",
        Category = AccountCategory.Asset
    };

    /// <summary>
    /// Asset reserve account used to manage currency conversion liquidity
    /// and foreign exchange operations.
    /// </summary>
    /// <remarks>
    /// Represents platform-controlled reserves dedicated to supporting
    /// multi currency operations, FX exposure management, and exchange
    /// rate stabilization.
    ///
    /// This account allows foreign exchange flows to be separated from
    /// operational treasury balances.
    /// </remarks>
    public static readonly LedgerAccount PlatformFxReserve = new()
    {
        Id = "asset:platform:fx_reserve",
        Name = "Platform FX Reserve (Currency Buffer)",
        AccountType = "platform_asset",
        Category = AccountCategory.Asset
    };

    /// <summary>
    /// Liability account representing taxes collected but not yet remitted
    /// to tax authorities.
    /// </summary>
    /// <remarks>
    /// Tracks obligations related to VAT, sales tax, and other platform
    /// tax liabilities generated by financial operations.
    ///
    /// Amounts recorded here represent funds owed externally and should be
    /// settled through appropriate tax payment workflows.
    /// </remarks>
    public static readonly LedgerAccount TaxPayable = new()
    {
        Id = "liability:platform:tax",
        Name = "Tax Payable (VAT/Sales Tax)",
        AccountType = "platform_liability",
        Category = AccountCategory.Liability
    };
}