using Microsoft.Extensions.Logging;
using ModularityKit.Mutator.Abstractions.Context;
using ModularityKit.Mutator.Abstractions.Engine;
using Polly;
using Polly.Retry;
using Ryze.Application.Features.Ledger.Interfaces.Executors;
using Ryze.Application.Features.Ledger.Interfaces.Helpers;
using Ryze.Application.Features.Ledger.Mutations.Transaction;
using Ryze.Application.Shared.Locking;
using Ryze.Domain.Features.Ledger.Entity;
using Ryze.Domain.Features.Ledger.Enum;
using Ryze.Domain.Features.Ledger.Events.Transaction;
using Ryze.Domain.Features.Ledger.Exceptions;
using Ryze.Domain.Features.Ledger.Repositories;
using Ryze.Domain.Shared;
using Ryze.Domain.Shared.Exceptions.Locks;

namespace Ryze.Application.Features.Ledger.Executors;

/// <summary>
/// Executes ledger transactions and coordinates the technical transaction recording lifecycle.
/// </summary>
/// <remarks>
/// Handles period validation, distributed locking, idempotency checks, sequential entry number
/// allocation, mutation execution, domain event publication, and mutation side effect processing.
/// Also provides operations for clearing pending entries belonging to an existing transaction.
/// Lock acquisition failures are automatically retried using an exponential backoff strategy.
/// </remarks>
public sealed class LedgerTransactionExecutor(
    IMutationEngine engine,
    IJournalEntryRepository entryRepo,
    ILedgerEntryNumberGenerator entryNumberGen,
    IEventPublisher eventPublisher,
    ILockProvider lockProvider,
    ILedgerPeriod periodService,
    ILogger<LedgerTransactionExecutor> logger)
    : ILedgerTransactionExecutor
{
    private readonly AsyncRetryPolicy _retryPolicy = Policy
        .Handle<LockAcquisitionFailedException>()
        .WaitAndRetryAsync(
            3,
            retryAttempt => TimeSpan.FromMilliseconds(Math.Pow(2, retryAttempt) * 100),
                (exception, delay, retryCount, _) =>
                {
                    logger.LogWarning(
                        exception,
                        "Lock acquisition failed. Retrying after {Delay} " +
                        "(Attempt {RetryCount})",
                        delay,
                        retryCount);
                });

    /// <summary>
    /// Executes ledger transaction through the complete transaction recording pipeline.
    /// </summary>
    /// <remarks>
    /// The operation is executed through a retry policy that retries lock acquisition failures
    /// using exponential backoff. Other exceptions are propagated without retry.
    /// </remarks>
    /// <param name="transaction">The ledger transaction to record.</param>
    /// <param name="ct">Token that can be used to cancel the asynchronous operation.</param>
    public Task<LedgerTransaction> ExecuteAsync(LedgerTransaction transaction, CancellationToken ct = default) =>
        _retryPolicy.ExecuteAsync(() => ExecuteInternalAsync(transaction, ct));

    /// <summary>
    /// Executes the internal ledger transaction recording workflow without applying the outer retry policy.
    /// </summary>
    /// <remarks>
    /// Validates the accounting period, acquires all required account and transaction locks,
    /// checks idempotency, allocates a sequential entry number, executes the transaction mutation,
    /// and publishes events generated by mutation side effects.
    /// </remarks>
    /// <param name="transaction">The ledger transaction to record.</param>
    /// <param name="ct">Token that can be used to cancel the asynchronous operation.</param>
    /// <returns>The recorded ledger transaction.</returns>
    /// <exception cref="LedgerPeriodClosedException">Thrown when the transaction timestamp belongs to a period that does not accept entries. </exception>
    /// <exception cref="LockAcquisitionFailedException">Thrown when one or more required locks cannot be acquired.</exception>
    /// <exception cref="LedgerValidationException">Thrown when the transaction mutation fails validation or does not produce a valid new state. </exception>
    private async Task<LedgerTransaction> ExecuteInternalAsync(
        LedgerTransaction transaction,
        CancellationToken ct)
    {
        logger.LogDebug(
            "Executing ledger transaction recording: " +
            "Id={TransactionId}, Type={Type}, IdempotencyKey={IdempotencyKey}",
            transaction.Id,
            transaction.Type,
            transaction.IdempotencyKey);

        await periodService.EnsurePeriodOpenAsync(transaction.Timestamp, ct: ct);

        var lockKeys = transaction.Entries
            .Select(entry => $"ledger:account:{entry.Account.AccountId}")
            .Append($"ledger:tx:{transaction.IdempotencyKey}")
            .Distinct(StringComparer.Ordinal)
            .OrderBy(
                key => key,
                StringComparer.Ordinal)
            .ToArray();

        await using var handles = await lockProvider.AcquireMultiAsync(
            lockKeys,
            TimeSpan.FromSeconds(30),
            ct);

        handles.StartAutoRenewal(
            TimeSpan.FromSeconds(20),
            TimeSpan.FromSeconds(30));

        if (!string.IsNullOrWhiteSpace(transaction.IdempotencyKey))
        {
            var existing = await entryRepo.GetByIdempotencyKeyAsync(
                transaction.IdempotencyKey,
                ct);

            if (existing is not null)
            {
                logger.LogInformation(
                    "Transaction already processed: " +
                    "IdempotencyKey={IdempotencyKey}, " +
                    "OriginalTransactionId={TransactionId}",
                    transaction.IdempotencyKey,
                    existing.TransactionId);

                var existingEntries = await entryRepo.GetTransactionEntriesAsync(
                    existing.TransactionId,
                    ct);

                return transaction with
                {
                    Id = existing.TransactionId,
                    Entries = existingEntries.ToList()
                };
            }
        }

        await handles.RenewAllAsync(TimeSpan.FromSeconds(30));

        var entryNumber = await entryNumberGen.GetNextEntryNumberAsync(ct);

        var finalizedTransaction = transaction with
            {
                Entries = transaction.Entries
                    .Select(entry => entry with
                        {
                            EntryNumber = entryNumber
                        })
                    .ToList()
            };

        var mutationContext = MutationContext.System(finalizedTransaction.InitiatedBy, finalizedTransaction.Reason ?? "Record ledger transaction") with
        {
            Mode = MutationMode.Commit
        };

        var mutation = new RecordTransactionMutation(finalizedTransaction, mutationContext);
        var result = await engine.ExecuteAsync(mutation, null!, ct);

        if (!result.IsSuccess || result.NewState is null)
        {
            var errors = result.ValidationResult.Errors
                .Select(error => error.Message)
                .Where(message => !string.IsNullOrWhiteSpace(message))
                .ToArray();

            throw new LedgerValidationException(
                "Ledger mutation failed",
                errors);
        }

        var recordedTransaction = result.NewState;

        foreach (var sideEffect in result.SideEffects)
        {
            // TODO: Replace direct LedgerTransactionRecorded construction with
            // LedgerTransactionRecordedSideEffectData from the mutation side effect.
            // The side effect payload should be passed directly to the event publisher
            // instead of reconstructing the event from recordedTransaction and entryNumber.
            var recordedEvent = new LedgerTransactionRecorded(
                recordedTransaction.Id,
                recordedTransaction.Timestamp,
                recordedTransaction.Entries,
                recordedTransaction.Type.ToString(),
                recordedTransaction.IdempotencyKey,
                recordedTransaction.InitiatedBy,
                recordedTransaction.Reason,
                entryNumber);

            await eventPublisher.PublishAsync(recordedTransaction.Id, recordedEvent, ct);
            
            logger.LogDebug(
                "Processed mutation side effect: {Type} " +
                "(Contract={Contract}@v{Version}) - {Description}",
                sideEffect.Type,
                sideEffect.DataContractType,
                sideEffect.DataContractVersion,
                sideEffect.Description);
        }

        logger.LogInformation(
            "Ledger transaction {TransactionId} recorded successfully " +
            "with entry number {EntryNumber}",
            recordedTransaction.Id,
            entryNumber);

        return recordedTransaction;
    }

    /// <summary>
    /// Clears all pending entries belonging to recorded ledger transaction.
    /// </summary>
    /// <remarks>
    /// Loads all entries associated with the transaction, acquires locks for all affected accounts
    /// and the transaction, and executes a clear mutation for the pending entries.
    /// Mutation side effects are published as <see cref="LedgerTransactionCleared"/> events.
    /// If the transaction does not exist or contains no pending entries, the operation completes
    /// without making any changes.
    /// </remarks>
    /// <param name="transactionId">The identifier of the transaction whose pending entries should be cleared.</param>
    /// <param name="ct">Token that can be used to cancel the asynchronous operation.</param>
    /// <exception cref="LockAcquisitionFailedException">Thrown when the required account or transaction locks cannot be acquired. </exception>
    /// <exception cref="LedgerValidationException">Thrown when the clear transaction mutation fails validation or cannot be committed. </exception>
    public async Task ClearAsync(
        Guid transactionId,
        CancellationToken ct = default)
    {
        var entries = await entryRepo.GetTransactionEntriesAsync(transactionId, ct);

        if (entries.Count == 0)
        {
            logger.LogWarning(
                "Cannot clear transaction {TransactionId}: no entries found",
                transactionId);

            return;
        }

        var accountIds = entries.Select(entry => entry.Account.AccountId)
            .Distinct()
            .OrderBy(
                id => id,
                StringComparer.Ordinal)
            .ToArray();

        var lockKeys = accountIds.Select(id => $"ledger:account:{id}")
            .Append($"ledger:tx:{transactionId}")
            .OrderBy(
                key => key,
                StringComparer.Ordinal)
            .ToArray();

        await using var handles = await lockProvider.AcquireMultiAsync(
            lockKeys,
            TimeSpan.FromSeconds(30), ct);

        handles.StartAutoRenewal(
            TimeSpan.FromSeconds(20),
            TimeSpan.FromSeconds(30));

        var pendingEntries = entries
            .Where(entry =>
                entry.Posting.Status ==
                EntryStatus.Pending)
            .ToList();

        if (pendingEntries.Count == 0)
        {
            logger.LogInformation(
                "Transaction {TransactionId} has no pending entries to clear",
                transactionId);

            return;
        }

        await handles.RenewAllAsync(TimeSpan.FromSeconds(30));

        var entryIds = pendingEntries
            .Select(entry => entry.Id)
            .ToList();

        var mutationContext = MutationContext.System("System", "Clear ledger transaction") with
        {
            Mode = MutationMode.Commit
        };

        var mutation = new ClearTransactionMutation(
            transactionId,
            entryIds,
            mutationContext);

        var result = await engine.ExecuteAsync(mutation, Guid.Empty, ct);

        if (!result.IsSuccess)
        {
            var errors = result.ValidationResult.Errors
                .Select(error => error.Message)
                .Where(message => !string.IsNullOrWhiteSpace(message))
                .ToArray();

            throw new LedgerValidationException(
                "Ledger clear mutation failed",
                errors);
        }

        foreach (var sideEffect in result.SideEffects)
        {
            // TODO: Publish LedgerTransactionClearedSideEffectData directly instead of
            // reconstructing LedgerTransactionCleared from the mutation input state.
            var clearedEvent = new LedgerTransactionCleared(
                transactionId,
                entryIds,
                DateTimeOffset.UtcNow);

            await eventPublisher.PublishAsync(transactionId, clearedEvent, ct);

            logger.LogDebug(
                "Processed mutation side effect: {Type} " +
                "(Contract={Contract}@v{Version}) - {Description}",
                sideEffect.Type,
                sideEffect.DataContractType,
                sideEffect.DataContractVersion,
                sideEffect.Description);
        }

        logger.LogInformation(
            "Transaction {TransactionId} cleared successfully. " +
            "Cleared entries: {EntryCount}",
            transactionId,
            entryIds.Count);
    }
}